import Header from '@/components/Header'; 
// Import the Header component from the @/components directory.
import './globals.css';
import { ReactNode } from 'react';

// Define the props for the RootLayout component
interface RootLayoutProps {
  children: ReactNode;
  // Define the props interface for the RootLayout component, which includes a single prop children of type ReactNode
}

// Metadata for the page
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-[#1A1A1A] h-screen relative">
        <div>
          {/* Include the Header component */}
          <Header />
          <div className="flex items-center justify-center -mt-4 z-10">
              {/* Render the child components */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
