import Header from '@/components/Header';
import './globals.css';
import { ReactNode } from 'react';

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-[#1A1A1A] h-screen relative">
        <div>
          <Header />
          <div className="flex items-center justify-center -mt-4 z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
